name: Build macOS App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install py2app
        run: |
          python3 -m pip install --upgrade pip
          pip install py2app

      - name: Build .app
        run: |
          python3 setup.py py2app

      - name: Upload .app as artifact
        uses: actions/upload-artifact@v4
        with:
          name: SlashCode-macOS-App
          path: dist/
